NUM_TOKENS = 6741062 * 10 # number of tokens in dataset
SEQ_LENGTH = 2048
ESTIMATED_TRAIN_ITEMS = NUM_TOKENS / SEQ_LENGTH
PER_GPU_BATCH = 16
NUM_GPUS = 1
GRADIENT_STEPS = 1
TOTAL_STEPS = ESTIMATED_TRAIN_ITEMS / (NUM_GPUS * (PER_GPU_BATCH * GRADIENT_STEPS))
print(TOTAL_STEPS)

